### ISSUE TITLE
Is this a MIT, GPL License ?

### ISSUE THREAD

**Issue by domeger** [rohitkhatri/Center-Loader#1]
We need to validate that you have some type of License agreement associated with this project.

**Comment by rohitkhatri** [comment]
I don't know much about the license, but what I know is It's free and anyone can use it change it and do whatever wants to do, can you suggest for that what license should I use?

**Comment by rohitkhatri** [comment]
I have added the MIT license.

**Comment by domeger** [comment]
Perfect, Thanks You 👍
